---
title: "Assignment 5"
author: "EPsy 8282"
date: "Fall 2017"
header-includes:
   - \usepackage{mathspec}
   - \usepackage{xcolor}
   - \usepackage{booktabs}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
   - \definecolor{myorange}{HTML}{EA6153}
output: 
  pdf_document:
    highlight: tango
    latex_engine: xelatex
    fig_width: 6
    fig_height: 6
mainfont: "Bembo Std"
sansfont: "Helvetica Neue UltraLight"
monofont: Inconsolata
urlcolor: "umn2"
always_allow_html: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
sleep = read.csv(file = "~/Dropbox/epsy-8282/data/sleep.csv")
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggjoy)
```

Please submit your responses to each question in a printed document. Also, please adhere to the following guidelines for further formatting your assignment: 

- All graphics should be resized so that they do not take up more room than necessary and should have an appropriate **caption** and **labels**. 
- Any typed mathematics (equations, matrices, vectors, etc.) should be appropriately typeset within the document using Equation Editor, Markdown, or \LaTeX. 

This assignment is worth 17 points. Each question is worth 1 point unless otherwise noted. 

\rule{0.5\linewidth}{\linethickness}

For this assignment, you will use the file *sleep.csv*. This file contains data from 18 people who participated in a sleep deprivation study. On Day 0 the participants were allowed their normal amount of sleep. Each of the subsequent nine nights (Day 1 to Day 9), they were restricted to 3 hours of sleep per night. Each day the participants were given a series of reaction time tests and the average time (in milliseconds) was computed and recorded. The data, which are the same data used in Assignment 2, come from: Belenky, G., Wesensten, N. J., Thorne, D. R., Thomas, M. L., Sing, H. C., Redmond, D. P., Russo, M. B. \& Balkin, T. J. (2003). Patterns of performance degradation and restoration during sleep restriction and subsequent recovery: A sleep dose-response study. *Journal of Sleep Research, 12*, 1--12.

This assignment focuses on inference for two covariates, GPA and female. All models considered in this lab will have (1) a linear change curve; and (2) random effects for the intercept and slope. The models considered will have only different numbers of static predictors. This assignment is worth 20 points. Each question is worth 1 point unless otherwise noted.

## Model Selection using Information Criteria

Suppose your research is concerned with gender differences in cognition under sleep deprivation. In addition to collecting the gender of your subjects, you also collected their grade point average (GPA) as you thought this might be a possible mediator of any gender differences. Based on substantive theory, the extent literature, your professional expertise, and common sense, you formulate the following verbal descriptions of five working hypotheses:

- **Hypothesis 1:** Gender differences and GPA difference are negligible (not significant).
- **Hypothesis 2:** Males on average have higher initial scores than females and this difference persists over
time.
- **Hypothesis 3:** Initial gender differences are mediated by GPA, at least partially.
- **Hypothesis 4:** Males on average have higher initial scores than females but the magnitude of the difference
changes over time.
- **Hypothesis 5:** Initial gender differences and differences over time are mediated by GPA, at least partially.

You will translate these working hypotheses into LMER models and estimate the models. Then you will use information criteria to evaluate the hypotheses.  

1. Create a publication quality table (formatting, caption, etc.) that presents the AICc, $\Delta$AICc, weight of evidence (Akaike Weights; $W$), and evidence ratio ($ER$) for the five candidate models. Present them in order from most to least probable. **(3pts.)**

2. Is the hypothesis asscoiated with the most probable model "true"? Explain.

3. Can you tell from the criteria whether the most probable model fits the data well (i.e., is it a "good" model)? How would you check to see if it is "good" model? Explain.

4. Interpret the weight of evidence for the most probable hypothesis.

5. Interpret the evidence ratio for the least probable hypothesis.

6. Based on the evidence, which hypotheses would you reject? Explain.

7. Based on the evidence, which hypotheses would you retain? Explain.

8. In a replication of this study, would the most probable hypothesis identified here again be the most probable? Explain.

9. Using the fixed effects estimates from the most probable model, describe the nature of the differences referred to in the verbal description of the hypothesis.

## Model Selection using *p*-Values

Using information crieria for model selection has many advantages, such as the direct evaluation of theory-driven models; those identified prior to data collection. A less attractive, but popular alternative to the multimodel approach, is to select models using a *Null Hypothesis Significance Testing* (NHST) strategy. 

In the second part of this assignment you will consider a "step-up" planned approach using NHST. Suppose that based on theory, the extent literature, your professional expertise, and common sense, you plan to begin by fitting a model that has no covariates (time is the only predictor). Then your "step-up" analysis proceded by including predictors, one at a time, in the following order:

- **Step 1.** Add the main effect of gender.
- **Step 2.** Add the main effect of GPA. 
- **Step 3.** Add interaction effect between gender and time. 
- **Step 4.** Add interaction effect between GPA and time.

At each step continue to include the effects of the previous steps. In  "step-up" analysis, the predictor terms will be accumulated regardless of their significance. After all the models have been fitted, you will judge their results. As in the previous section, all models should have (1) a linear change curve; and (2) random effects for the intercept and slope. In the questions that follow, consider a result statistically significant when $p < 0.05$.

10. Create a publication quality table (formatting, caption, etc.) that presents the results from using Likelihood Ratio Tests to compare the models at each stage in the "step-up" analysis. Label the models from 0 to 4, where Model 0 includes only the effect of time; no covariates. **(2pts.)**

11. In words (not symbols), what is the null hypothesis associated with Step 1?

12. Is there evidence that a main effect of gender should be included in the model? Explain.

13. Is there evidence that GPA mediates the effect of gender? Explain.

14. Is there evidence that an interaction effect between gender and time should be included in the model? Explain.

15. Is there evidence that an interaction effect between GPA and time should be included in the model? Explain.

16. Which model would you adopt based on the results of the "step-up" approach? Explain.

17. In the "step-up" approach you carried out several statistical tests. Is this multiple testing an issue with the NHST approach? Explain.
