---
title: "Assignment 08"
author: "Multilevel Regression Models - Longitudinal Analysis"
header-includes:
   - \usepackage{xcolor}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
output: 
  pdf_document:
    highlight: tango
urlcolor: "umn2"
---

This assignment is intended to give you experience working with multilevel regression models to analyze longitudinal data. *Do not include any R syntax or output unless it is specifically required in the question.* Please submit your responses to each of the questions below. Please submit your responses to each of the questions below in a printed document. All graphics should be resized so that they do not take up more room than necessary and should have an appropriate caption. All tables should also have an appropriate caption.

This assignment is worth 20 points. Each question is worth 1 point unless otherwise noted. 

\rule{0.5\linewidth}{\linethickness}

For this assignment, you will use the file, *NHL-Wide.csv*. This file contains 9 years of data on 31 NHL teams. The variables in this file are:

- `team`: NHL team name
- `established`: Year the team was established 
- `division`: Division the team plays in
- `X2002` -- `X2014`: Fan cost index (FCI) for the years 2002--2014. There are no data for 2012, since that year the NHL was locked out. The FCI comprises the prices of four (4) average-price tickets, two (2) small draft beers, four (4) small soft drinks, four (4) regular-size hot dogs, parking for one (1) car, two (2) game programs and two (2) least-expensive, adult-size adjustable caps. Costs were determined by telephone calls with representatives of the teams, venues and  concessionaires. Identical questions were asked in all interviews. 
- `location`: Location of the team
- `stadium`: Name of the arena where the team plays
- `yearOpened`: The year the arena opened
- `lat`: Latitude (north/south) of the arena
- `lon`: Longitude (east/west) of the arena
- `capacity`: Capacity of the arena

You will use these data to examine (1) the effect of time on FCI, and (2) the effect of latitude on FCI.

# Preparation

To begin the assignment, first select only the following variables:

- The team name
- All the variables containing the yearly FCI values
- Latitude

This should result in a data frame with 31 rows and 11 columns. 

Then, *gather* the data into the long format and assign it to another data frame for use in some of the analyses. This should result in a data frame with 279 rows and 4 columns. Assign the FCI values to a variable called `fci` and the years to a variable called `year` in this long data frame.

Finally, change the levels of the *year* variable to remove the `X` from each level (e.g., `X2002` becomes `2002`, etc.), and coerce the year variable into a numeric variable. Running `str()` on your data frame should show that the year variable is numeric or integer.

\pagebreak

If all went well, the structure of your data should look like the following:

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(lme4)
library(tidyr)
nhl = read.csv(file = "/Users/andrewz/Documents/EPsy-8252/data/NHL-Wide.csv")

# Select variables
nhl2 = nhl %>% dplyr::select(team, X2002, X2003, X2006, X2007, X2008, X2010, X2011, X2013, X2014, lat)

# Create long data from wide data (need tidyr package loaded)
nhlLong = nhl2 %>% gather(
  key = year, # Name of the variable that delineates the time points
  value = fci, # Name of the outcome
  c(X2002, X2003, X2006, X2007, X2008, X2010, X2011, X2013, X2014)
  )

# Make years numeric
nhlLong$year = as.factor(nhlLong$year)
levels(nhlLong$year) = c("2002", "2003", "2006", "2007", "2008", "2010", "2011", "2013", "2014")
nhlLong$year = as.numeric(as.character(nhlLong$year))
#str(nhlLong)
head(nhlLong)
```

# Data Exploration

1. Create a spaghetti plot of FCI over time for each team. In this plot, all teams should be in the same panel. Add the mean FCI over time as well. Make the teams' trajectories slightly transparent so that the mean trajectory is easily visible.

2. Create another spaghetti plot of FCI over time facetted by team. In this plot, each team should be in a separate panel.

3. Compute the mean and standard deviation of FCI conditioned on year. Present these in a table.

4. What do the plots and numerical summaries suggest about whether there differences in FCI over time? Explain.


# Unconditional Models

5. Begin by centering the year predictor, and fitting the unconditional means model, the unconditional linear growth model, and the unconditional quadratic growth model, all with only a random-effect for intercept. Label these models, *Model A*, *Model B*, and *Model C* respectively, and include the results from these models in a table of model results. Be sure to include any goodness-of-fit and/or pseudo-$R^2$ measures for each model that you feel are appropriate. You will be using the results from these three models to determine the structure of the Level-1 model, so be sure to use an appropriate method of estimating the effects. Model your table after the table posted in the *13-multilevel-models-table.pdf* notes (on the course website). **(3pts.)**

6. Based on the results of fitting the unconditional models, adopt a structure of the Level-1 model. Explain why you adopted this structure.

7. Using the  adopted structure for the Level-1 model, examine which random-effects are needed. Report the pertinent results from any models you may have fitted in this investigation by writing prose that is suitable for publication. If you perform any other statistical analyses during this investigation that help you make your decision, report the results of these analyses as well. Remember to use an appropriate method of estimating the effects for examining random-effects.

8. Now that you have adopted the structures for both the fixed-effects (level-1) and random-effects (level-2) for the unconditional model, write the multilevel *and* composite equations for your adopted model. **(2pts.)**

\pagebreak

# Effect of Latitude

9. Using your adopted structure for the fixed- and random-effects, now also include an effect of latitude in (1) the Level-2 intercept model (*Model D*); (2) the Level-2 intercept and linear slope model (*Model E*); and (3) the level-2 intercept, linear slope, and quadratic slope model (*Model F*). Include the results from fitting these models in the table of model results (now should have six models included). Be sure to include any goodness-of-fit and/or pseudo-$R^2$ measures for the model that you feel are appropriate. **(2pts.)**

10. Which model should be adopted. Explain.


# Plot of Model Results

11. Create a single display of the fixed effects from your final adopted fitted equation. The plot you create should highlight the effect of time on FCI. Also show the effects of latitude by plotting separate lines. This plot should be suitable for publication. **(2pts.)**

12. Create a single display to compare the fitted equations for at least two teams (of your choice). The plot you create should highlight the effect of time on FCI. This plot should be suitable for publication. **(2pts.)**

13. Write 2--3 sentences that help a reader understand the effect of time and latitude on FCI. **(2pts.)**


