---
title: "Assignment 05"
author: "Mixed-Effects Regression Models"
header-includes:
   - \usepackage{xcolor}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
output: 
  pdf_document:
    highlight: tango
urlcolor: "umn2"
---

This assignment is intended to give you experience fitting and interpreting mixed-effects regression models. Turn in a printed document that includes your responses to each of the questions on this assignment. This assignment is worth 14 points.

Please adhere to the following guidelines for further formatting your assignment: 

- All graphics should be resized so that they do not take up more room than necessary and should have an appropriate caption.
- Any typed mathematics (equations, matrices, vectors, etc.) should be appropriately typeset within the document.
- If you are using Markdown, all syntax should be hidden (i.e., not displayed) unless specifically asked for. Any messages or warnings produced from loading packages should also be hidden.


\rule{0.5\linewidth}{\linethickness}

For this assignment, you will use two files *popular-student.csv* and *popular-classroom.csv*. The first file contains data on 2000 different students. The variables in this file are:

- `student`: Student ID (within a school)
- `class`: Classroom ID 
- `popularity`: Popularity rating of the student (0-10 scale; where 0 = very unpopular and 10 = very popular) based on having all other students in the student's class rate him/her and computing the average of those ratings.
- `teachPop`: Student's popularity as rated by the teacher. Higher values are indicative of higher popularity
- `extra`: Extraversion of the student (measured on a 10-point scale)
- `female`: Sex of the student (Male = 0; Female = 1)

The second file contains data on 100 different classrooms. The variables in this file are:

- `class`: Classroom ID
- `teacherExp`: Experience level of teacher, in years

The data, provided by Hox (2002), were simulated from data collected as part of a sociological study of student popularity. Student popularity, a rating on a scale of 1--10, was derived by a sociometric procedure in which all students in a class rate all the other students. Each students' popularity is the average received popularity rating. Because of the sociometric procedure, group effects as apparent from higher level variance components, are rather strong and should be examined using multilevel regression models. 

Hox, J. J. (2002). *Multilevel analysis: Techniques and applications.* Mahwah, NJ: Lawrence Erlbaum Associates.

\newpage

## Preparation

To begin the assignment, you will need to merge the two datasets. This should result in a data frame with 2000 rows and 7 variables. 

## Unconditional Means Model

1. Using variable names, write the equation for the statistical model that specifies the unconditional means model. (Don't forget about the distributional assumptions!)

Fit the unconditional means model with a random-effect of intercept (henceforth referred to as Model 0). Be sure you fit this model using maximum likelihood estimation. Use the results of fitting this model to answer the questions in this section of the assignment.

2. Use the estimated variance components to determine the proportion of variation unaccounted for at the classroom- and student-level.


## Student-Level Fixed Effects

Fit the following three models listed below. Again, be sure you are fitting these using maximum likelihood estimation. (Note: These models should also include the fixed- and random-effect of intercept.)

- Model 1: Fixed effect of extraversion
- Model 2: Fixed effect of sex
- Model 3: Fixed effects of extraversion and sex 

3. Compute and report the AICc value for each of these models and for the unconditional means model (Model 0). 

4. Using the AICc values you computed in Question \#3, write the fitted equation for the model that has the most empirical support. (For the remainder of this section, this will be referred to as your adopted model.)

5. Based on the coefficient $t$-values for your adopted model, is there evidence to support the inclusion of the fixed effect for extraversion? What about that for sex? Explain.

6. Interpret the fixed effect for extraversion from your adopted model.

7. Interpret the fixed effect for sex from your adopted model.

\pagebreak

## Classroom-Level Fixed-Effects

8. Fit the model that includes all the effects from your adopted model from Question \#4 and the fixed-effect of teacher experience. Write the fitted equation for the this model.


9. Compute a table of model evidence for the five models fitted in this assignment. This table should include the following information for each of the candidate models. **(2pts.)**

    - Model
    - Log-likelihood
    - K
    - AICc
    - $\Delta$AICc
    - Evidence Ratio
    - Model Probability
    
10. Create a table that presents the coefficients, standard errors, variance components, and model-level evidence for the five models fitted in this assignment. If you are using an R function to create this table, be thoughtful about what information is presented; don't just use the defaults. For example, if the sample size is the same for all of the models, put that in the table caption rather than as a row in the table. (You may want to find a journal article from your field that includes a table of mixed-effects model results to inform your decisions about what should be included.) **(2pts.)**

11. Create a publication quality plot that displays the results for the model that has the most empirical evidence (based on your answer to Question \#10). **(2pts.)**
