# Schedule

Below is the tenative schedule for the class. The dates are subject to change at the instructor's discretion. Readings should be completed prior to class. Assignments are due at the beginning of the class period that they are due

<br />

## Calendar

<br />

<table class="table">
<tbody>

<tr>
<td colspan="3"><b>Unit 0: Introduction</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;width:5%;">&nbsp;</td>
<td style="width:15%;">Sept. 04</td>
<td style="vertical-align:middle;width:80%;">Introduction to EPsy 3264</td>
</tr>

<tr>
<td colspan="3">**Unit 1: Modeling and Simulation**</td>
</tr>

<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Sept. 09</td>
<td style="vertical-align:middle;">**_Reading:_** [Introduction](https://zief0002.github.io/statistical-thinking/introduction.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">**_Reading:_** [Modeling &amp; Simulation](https://zief0002.github.io/statistical-thinking/modeling-simulation.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Spotify Playlists</td>
</tr>


<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Sept. 11</td>
<td style="vertical-align:middle;">**_Reading:_** [Generating Data From Models](https://zief0002.github.io/statistical-thinking/generating-data-from-models.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Generating Random Data&mdash;Cat Factory</td>
</tr>


<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Sept. 16</td>
<td style="vertical-align:middle;">**_Reading:_** [Monte Carlo Simulation](https://zief0002.github.io/statistical-thinking/monte-carlo-simulation.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;1 Due (Learning TinkerPlots)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Introduction to Monte Carlo Simulation</td>
</tr>

<tr>
<td rowspan="1" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="1" style="vertical-align:middle;">Sept. 18</td>
<td style="vertical-align:middle;">Automating the Simulation Process</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Sept. 23</td>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;2 Due (Free Throws)**</td>

</tr>

<tr>
<td style="vertical-align:middle;" bgcolor="#e6eb81">**Group Quiz &#35;1**</td>
</tr>

<tr>
<td colspan="3">**Unit 2: Modeling Sampling Variation**</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Sept. 25</td>
<td style="vertical-align:middle;">**_Reading:_** [Modeling Sampling Variation](https://zief0002.github.io/statistical-thinking/modeling-sampling-variation.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Monday Breakups</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Sept. 30</td>
<td style="vertical-align:middle;">Features of Distributions</td>
</tr>

<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Oct. 02</td>
<td style="vertical-align:middle;">**_Reading:_** [Describing Distributions](https://zief0002.github.io/statistical-thinking/describing-distributions.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;3 Due (Distracted Driving)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Helper or Hinderer</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Oct. 07</td>
<td style="vertical-align:middle;">Comparing Hand Spans</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Oct. 09</td>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;4 Due (College Debt)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Racial Disparities in Police Stops</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Oct. 14</td>
<td style="vertical-align:middle;" bgcolor="#e6eb81">**Group Quiz &#35;2**</td>
</tr>

<tr>
<td colspan="3">**Unit 3: Experimental Variation and the Randomization Test**</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Oct. 16</td>
<td style="vertical-align:middle;">**_Reading:_** [Experimental Variation and the Randomization Test](https://zief0002.github.io/statistical-thinking/experimental-variation-and-the-randomization-test.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Memorization</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Oct. 21</td>
<td style="vertical-align:middle;">Memorization using TinkerPlots</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Oct. 23</td>
<td style="vertical-align:middle;">Sleep Deprivation</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Oct. 28</td>
<td style="vertical-align:middle;">**_Reading:_** [Quantifying Results: p-Value](https://zief0002.github.io/statistical-thinking/quantifying-results-p-value.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Contagious Yawns</td>
</tr>

<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Oct. 30</td>
<td style="vertical-align:middle;">**_Reading:_** [Internal Validity Evidence and Random Assignment](https://zief0002.github.io/statistical-thinking/internal-validity-evidence-and-random-assignment.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;5 Due (Dolphin Therapy)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Strength Shoe</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Nov. 04</td>
<td style="vertical-align:middle;" bgcolor="#e6eb81">**Group Quiz &#35;3**</td>
</tr>

<tr>
<td colspan="3">**Unit 4: Sampling Variation and the Bootstrap Test**</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Nov. 06</td>
<td style="vertical-align:middle;">**_Reading:_** [Sampling Variation and the Bootstrap Test](https://zief0002.github.io/statistical-thinking/sampling-variation-and-the-bootstrap-test.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Speed Skating</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Nov. 11</td>
<td style="vertical-align:middle;">**_Reading:_** [External Validity Evidence and Random Sampling](https://zief0002.github.io/statistical-thinking/external-validity-evidence-and-random-sampling.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Gettysburg Address</td>
</tr>

<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Nov. 13</td>
<td style="vertical-align:middle;">**_Reading:_** [Validity Evidence and Inferences](https://zief0002.github.io/statistical-thinking/validity-evidence-and-inferences.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">**_Reading:_** [Observational Studies and the Bootstrap Test](https://zief0002.github.io/statistical-thinking/observational-studies-and-the-bootstrap-test.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Murderous Nurse</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Nov. 18</td>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;6 Due (Lyric Readability)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Movie Sequels</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Nov. 20</td>
<td style="vertical-align:middle;" bgcolor="#e6eb81">**Group Quiz &#35;4**</td>
</tr>

<tr>
<td colspan="3">**Unit 5: Estimating Uncertainty**</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Nov. 25</td>
<td style="vertical-align:middle;">**_Reading:_** [Estimating Uncertainty](https://zief0002.github.io/statistical-thinking/estimating-uncertainty.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;">Kissing the ‘Right’ Way</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Nov. 27</td>
<td style="vertical-align:middle;" bgcolor="#cc79a7">**No Class: Take a well-earned break**</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Dec. 02</td>
<td style="vertical-align:middle;">Cuddling Preferences</td>
</tr>

<tr>
<td rowspan="3" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="3" style="vertical-align:middle;">Dec. 04</td>
<td style="vertical-align:middle;">**_Reading:_** [Uncertainty and Bias](https://zief0002.github.io/statistical-thinking/uncertainty-and-bias.html)</td>
</tr>

<tr>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;7 Due (College Student Health Survey)**</td>
</tr>

<tr>
<td style="vertical-align:middle;">Minnesota College Debt</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Dec. 09</td>
<td style="vertical-align:middle;">Comparing Cuddling Preferences</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td style="vertical-align:middle;">Dec. 11</td>
<td style="vertical-align:middle;" bgcolor="#e6eb81">**Group Quiz &#35;5**</td>
</tr>

<tr>
<td rowspan="2" align="center" style="vertical-align:middle;">&nbsp;</td>
<td rowspan="2" style="vertical-align:middle;">Dec. 12</td>
<td style="vertical-align:middle;" bgcolor="#bccBd8">**Assignment &#35;8 Due (Dolphins and Pigs)**<br />Due by 12:00pm in EdSciB 250</td>
</tr>

</tbody>
</table>    

